# Generated by Django 3.2.3 on 2021-05-18 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_products_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
